const STRINGS = {
	EDIT_PRIVACY_POLICY:'Edit Privacy Policy',
	ADD_EVENT:'Add Event',
	UPDATE_BLOG:"Update Blog",
	PRIVACY_POLICY:'Privacy Policy',
	CONTACT_FORM:'Contact Form',
	TERMSANDCONDTIONS:'Term and conditions',
	DEALS:'Deals',
	EVENTS:'Events',
	VIEW_EVENTS:'View Events',
	BLOGS:' Blogs',
	VIEW_BLOGS:'View Blog',
	ADD_BLOGS:'ADD Blog',
	CATEGORY:' Category',
	VIEW_CATEGORY:'View Category',
	ADD_CATEGORY:'Add Category',
	NETWORK:' Network',
	VIEW_NETWORK:'View Network',
	ADD_NETWORK:'Add Network',
	STORE:'Stores',
	ADD_STORES:'Create Store',
	SINGLE_STORE:'Single Store',
	MANAGE_COUPONS:" Coupons",
	MANAGE_PRODUCTS: " Products",
	USERNAME: "Username",
	OPRATIONNAME: "Operations",
	ADD_USER:"Add User",
	USER:'Users',
	OPRATION:"Operation List",
	REMEMBER_ME: "Remember Me",
	PASSWORD: "Password",
	FIRSTNAME: "First Name",
	FULLNAME: "Full Name",
	LASTNAME: "Last Name",
	EMAIL: "Email",
	ADDRESS: "Address",
	INTRODUCTION: "Describe Yourself",
	COUNTRY: "Country",
	PROVINCE: "Province",
	EDUCATION: "Education",
	CITY: "City",
	INTERESTS: "Interests",
	CERTIFICATE: "certificate",

	ITEM_DASHBOARD: "Item Dashboard",
	MANAGE_TEACHER: " Teacher",
	STUDENTS: "Students",
	MANAGE_TEACHER_CREATE: "Create New Teacher",
	TEACHER_PROFILE: "Teacher Profile",
	ADMIN_DASHBOARD: "Dashboard",
	USER_DAHSBOARD: "User Dashboard",
	TEACHER_STUDENT_PROFILE_VIEW: "Student Profile",

	INSTITUTE_PROFILE: "Institute Profile",
	INSTITUTE_SETTINGS: "Settings",
	MANAGE_STUDENTS: " Users",
	MANAGE_OPRATION: "Operations",
	MANAGE_OPRATION_CREATE: "Add Operation",
	MANAGE_OPRATION_UPDATE: "Update Operation",
	INSTITUTE: "Institute Name",

	FINANCE: "Finance",
	REQUESTS: "Requests",
	REGISTRATION_REQUEST: "Registration",
	COURSE_REQUEST: "Course",
	COUPONS: "Coupons",
	COUPONS_CREATE: "Generate New Coupons",
	ENROLLED_STUDENTS: "Enrolled Students",
	EARNINGS: "Earnings",
	VIEW_EARNINGS: "Earnings",
	STUDENTS_EARNINGS: "Earnings",
	MANAGE_STORES: " Stores",
	COURSE_VIEW: "View Course ",
	NEW_COURSE: "Create New Course",
	COURSE_NAME: "Enter Course Name",
	COURSE_SUBTITLE: "Enter Course Subtitle",

	STUDENT_PROFILE: "Student Profile",
	STUDENT_DASHBOARD: "Dashboard",
	STUDENT_ASSIGNMENTS: " Assignment",
	STUDENT_QUIZZES: " Quizzes",
	STUDENT_COURSE_VIEW: "Lectures",
	STUDENT_GRADING: "Grading",
	STUDENT_GRADE_ASSIGNMENTS: "Assignment",
	STUDENT_GRADE_QUIZZES: "Quizzes",
	STUDENT_ENROLLED_COURSES: "Operations",
	AGE: "Age",
	PHONE: "Phone No",
};

export default STRINGS;
