import WEB_PAGES from "../pages/index.ts";
import PATH from "./Path.ts";
import ProtectedRoute from "./Routes/ProtectedRoute.tsx";
import PublicRoute from "./Routes/PublicRoute.tsx";
import { RouteType } from "./type";
import STRINGS from "../utils/strings";

const PRIVATE_ROUTES: RouteType[] = [
	{
		name: STRINGS.ITEM_DASHBOARD,
		path: PATH.ITEM_DASHBOARD,
		page: <WEB_PAGES.ITEM_DASHBOARD />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.MANAGE_TEACHER,
		path: PATH.MANAGE_TEACHER,
		page: <WEB_PAGES.MANAGE_TEACHER />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.MANAGE_OPRATION,
		path: PATH.MANAGE_OPRATION,
		page: <WEB_PAGES.MANAGE_OPRATION />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.STUDENTS,
		path: PATH.STUDENTS,
		page: <WEB_PAGES.STUDENTS />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.MANAGE_STUDENTS,
		path: PATH.MANAGE_STUDENTS,
		page: <WEB_PAGES.MANAGE_STUDENTS />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.MANAGE_TEACHER_CREATE,
		path: PATH.MANAGE_TEACHER_CREATE,
		page: <WEB_PAGES.MANAGE_TEACHER_CREATE />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.MANAGE_OPRATION_CREATE,
		path: PATH.MANAGE_OPRATION_CREATE,
		page: <WEB_PAGES.MANAGE_OPRATION_CREATE />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.MANAGE_OPRATION_UPDATE,
		path: PATH.MANAGE_OPRATION_UPDATE,
		page: <WEB_PAGES.MANAGE_OPRATION_UPDATE />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.MANAGE_TEACHER_CREATE,
		path: PATH.MANAGE_TEACHER_CREATE,
		page: <WEB_PAGES.MANAGE_TEACHER_CREATE />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.ADMIN_DASHBOARD,
		path: PATH.ADMIN_DASHBOARD,
		page: <WEB_PAGES.ADMIN_DASHBOARD />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.USER_DAHSBOARD,
		path: PATH.USER_DASHBOARD,
		page: <WEB_PAGES.USER_DASHBOARD />,
		routeType: ProtectedRoute,
		layout: "private",
	},

	{
		name: STRINGS.INSTITUTE_PROFILE,
		path: PATH.INSTITUTE_PROFILE,
		page: <WEB_PAGES.INSTITUTE_PROFILE />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.INSTITUTE_SETTINGS,
		path: PATH.INSTITUTE_SETTINGS,
		page: <WEB_PAGES.INSTITUTE_SETTINGS />,
		routeType: ProtectedRoute,
		layout: "private",
	},

	{
		name: STRINGS.COUPONS,
		path: PATH.COUPONS,
		page: <WEB_PAGES.COUPONS />,
		routeType: ProtectedRoute,
		layout: "private",
	},

	{
		name: STRINGS.COUPONS_CREATE,
		path: PATH.COUPONS_CREATE,
		page: <WEB_PAGES.COUPONS_CREATE />,
		routeType: ProtectedRoute,
		layout: "private",
	},

	{
		name: STRINGS.EARNINGS,
		path: PATH.EARNINGS,
		page: <WEB_PAGES.EARNINGS />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.REGISTRATION_REQUEST,
		path: PATH.REGISTRATION_REQUEST,
		page: <WEB_PAGES.REGISTRATION_REQUEST />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.COURSE_REQUEST,
		path: PATH.COURSE_REQUEST,
		page: <WEB_PAGES.COURSE_REQUEST />,
		routeType: ProtectedRoute,
		layout: "private",
	},

	{
		name: STRINGS.VIEW_EARNINGS,
		path: PATH.VIEW_EARNINGS,
		page: <WEB_PAGES.VIEW_EARNINGS />,
		routeType: ProtectedRoute,
		layout: "private",
	},

	{
		name: STRINGS.STUDENTS_EARNINGS,
		path: PATH.STUDENTS_EARNINGS,
		page: <WEB_PAGES.STUDENTS_EARNINGS />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.STORE,
		path: PATH.STORES,
		page: <WEB_PAGES.STORES />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.ADD_STORES,
		path: PATH.ADD_STORES,
		page: <WEB_PAGES.ADD_STORE />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.COURSE_VIEW,
		path: PATH.COURSE_VIEW_STUDENT,
		page: <WEB_PAGES.COURSE_VIEW />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.COURSE_VIEW,
		path: PATH.COURSE_VIEW,
		page: <WEB_PAGES.COURSE_VIEW />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.NEW_COURSE,
		path: PATH.NEW_COURSE,
		page: <WEB_PAGES.NEW_COURSE />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.TEACHER_PROFILE,
		path: PATH.TEACHER_PROFILE,
		page: <WEB_PAGES.TEACHER_PROFILE />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.STUDENT_PROFILE,
		path: PATH.STUDENT_PROFILE,
		page: <WEB_PAGES.STUDENT_PROFILE />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.STUDENT_DASHBOARD,
		path: PATH.STUDENT_DASHBOARD,
		page: <WEB_PAGES.STUDENT_DASHBOARD />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.STUDENT_ASSIGNMENTS,
		path: PATH.STUDENT_ASSIGNMENTS,
		page: <WEB_PAGES.STUDENT_ASSIGNMENTS />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.STUDENT_QUIZZES,
		path: PATH.STUDENT_QUIZZES,
		page: <WEB_PAGES.STUDENT_QUIZZES />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.STUDENT_GRADE_ASSIGNMENTS,
		path: PATH.STUDENT_GRADE_ASSIGNMENTS,
		page: <WEB_PAGES.STUDENT_GRADE_ASSIGNMENTS />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.STUDENT_GRADE_QUIZZES,
		path: PATH.STUDENT_GRADE_QUIZZES,
		page: <WEB_PAGES.STUDENT_GRADE_QUIZZES />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.STUDENT_ENROLLED_COURSES,
		path: PATH.STUDENT_ENROLLED_COURSES,
		page: <WEB_PAGES.STUDENT_ENROLLED_COURSES />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.STUDENT_COURSE_VIEW,
		path: PATH.STUDENT_COURSE_VIEW,
		page: <WEB_PAGES.STUDENT_COURSE_VIEW />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.MANAGE_STORES,
		path: PATH.STUDENT_COURSES_LIST,
		page: <WEB_PAGES.STUDENT_COURSES_LIST />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	//
	{
		name: STRINGS.TEACHER_STUDENT_PROFILE_VIEW,
		path: PATH.TEACHER_STUDENT_PROFILE_VIEW,
		page: <WEB_PAGES.TEACHER_STUDENT_PROFILE_VIEW />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.ADD_USER,
		path: PATH.CREATE_USER,
		page: <WEB_PAGES.ADD_USER />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.MANAGE_PRODUCTS,
		path: PATH.MANAGE_PRODUCTS,
		page: <WEB_PAGES.MANAGE_PRODUCTS />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.MANAGE_COUPONS,
		path: PATH.MANAGE_COUPONS,
		page: <WEB_PAGES.MANAGE_COUPONS />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.VIEW_BLOGS,
		path: PATH.VIEW_BLOG,
		page: <WEB_PAGES.VIEW_BLOG />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.ADD_BLOGS,
		path: PATH.ADD_BLOGS,
		page: <WEB_PAGES.ADD_BLOG />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.UPDATE_BLOG,
		path: PATH.UPDATE_BLOG,
		page: <WEB_PAGES.UPDATE_BLOG />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.VIEW_CATEGORY,
		path: PATH.VIEW_CATEGORY,
		page: <WEB_PAGES.VIEW_CATEGORY />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.ADD_CATEGORY,
		path: PATH.ADD_CATEGORY,
		page: <WEB_PAGES.ADD_CATEGORY />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.VIEW_NETWORK,
		path: PATH.VIEW_NETWORK,
		page: <WEB_PAGES.VIEW_NETWORK />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.ADD_CATEGORY,
		path: PATH.ADD_NETWORK,
		page: <WEB_PAGES.ADD_NETWORK />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.SINGLE_STORE,
		path: PATH.SINGLE_STORE,
		page: <WEB_PAGES.SINGLE_STORE />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.ADD_CATEGORY,
		path: PATH.SINGLE_CATEGORY,
		page: <WEB_PAGES.SINGLE_CATEGORY />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.ADD_CATEGORY,
		path: PATH.ALL_CATEGORY,
		page: <WEB_PAGES.ALL_CATEGORY />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.BLOGS,
		path: PATH.ALL_BLOG,
		page: <WEB_PAGES.ALL_BLOGS />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.BLOGS,
		path: PATH.SINGLE_BLOG,
		page: <WEB_PAGES.SINGLE_BLOG />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.DEALS,
		path: PATH.VIEW_DEALS,
		page: <WEB_PAGES.VIEW_DEALS />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.EVENTS,
		path: PATH.SINGLE_EVENT,
		page: <WEB_PAGES.SINGLE_EVENT />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.ADD_EVENT,
		path: PATH.ADD_EVENT,
		page: <WEB_PAGES.ADD_EVENT />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.VIEW_EVENTS,
		path: PATH.VIEW_EVENTS,
		page: <WEB_PAGES.VIEW_EVENTS />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.TERMSANDCONDTIONS,
		path: PATH.TERMS_CONDITIONS,
		page: <WEB_PAGES.TERMS_CONDITIONS />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.PRIVACY_POLICY,
		path: PATH.PRIVACY_POLICY,
		page: <WEB_PAGES.PRIVACY_POLICY />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.EDIT_PRIVACY_POLICY,
		path: PATH.EDIT_PRIVACY_POLICY,
		page: <WEB_PAGES.EDIT_PRIVACY_POLICY />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.EDIT_TERM_AND_CONDITIONS,
		path: PATH.EDIT_TERMS_CONDITIONS,
		page: <WEB_PAGES.EDIT_TERM_AND_CONDITIONS/>,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.CONTACT_FORM,
		path: PATH.CONTACT_FORM,
		page: <WEB_PAGES.CONTACT_FORM />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.SHIPPING_PAGE,
		path: PATH.SHIPPING_PAGE,
		page: <WEB_PAGES.SHIPPING_PAGE_VIEW />,
		routeType: ProtectedRoute,
		layout: "private",
	},
	{
		name: STRINGS.SHIPPING_PAGE_ALL,
		path: PATH.SHIPPING_PAGE_ALL,
		page: <WEB_PAGES.SHIPPING_PAGE_ALL />,
		routeType: ProtectedRoute,
		layout: "private",
	},
];

const AUTH_ROUTES: RouteType[] = [
	{
		name: "Login",
		path: PATH.LOGIN,
		page: <WEB_PAGES.LOGIN />,
		routeType: PublicRoute,
		layout: "auth",
	},
	{
		name: "Otp",
		path: PATH.OTP_SCREEN,
		page: <WEB_PAGES.OTP_SCREEN />,
		routeType: PublicRoute,
		layout: "auth",
	},

	{
		name: "Closed",
		path: PATH.CLOSED,
		page: <WEB_PAGES.CLOSED />,
		routeType: PublicRoute,
		layout: "auth",
	},
	{
		name: "SignUp",
		path: PATH.SIGNUP,
		// page: <WEB_PAGES.CLOSED />, //for temporary close signups
		page: <WEB_PAGES.SIGNUP />,
		routeType: PublicRoute,
		layout: "auth",
	},
	{
		name: "SignUp",
		path: PATH.INSTITUTE_SIGNUP,
		page: <WEB_PAGES.INSTITUTE_SIGNUP />,
		routeType: PublicRoute,
		layout: "auth",
	},

	{
		name: "ForgotPassword",
		path: PATH.FORGOT_PASSWORD,
		page: <WEB_PAGES.FORGOT_PASSWORD />,
		routeType: PublicRoute,
		layout: "auth",
	},

	{
		name: "UpdatePassword",
		path: PATH.UPDATE_PASSWORD,
		page: <WEB_PAGES.UPDATE_PASSWORD />,
		routeType: PublicRoute,
		layout: "auth",
	},
];

const ROUTES: RouteType[] = [...AUTH_ROUTES, ...PRIVATE_ROUTES];

export default ROUTES;
